# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo

  pod 'Alamofire', '~> 5.4.4'
  pod 'Moya/RxSwift', '~> 15.0.0'
  pod 'ObjectMapper', '~> 4.2.0'
  pod 'RxSwift', '~> 6.2.0'
end
