# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo

  pod 'Alamofire', '~> 5.6.1'
  pod 'Moya/RxSwift', '~> 15.0.0'
  pod 'ObjectMapper', '~> 4.2.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'SnapKit', '~> 5.6.0'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
  end

end
